spring:
  application:
    name: Delegation Poker
  messages:
      basename: messages
  thymeleaf:
    mode: HTML
server:
  compression:
    enabled: true
    mime-types:
     - "text/html"
     - "text/xml"
     - "text/plain"
     - "text/css"
     - "text/javascript"
     - "application/javascript"
     - "application/json"
     - "application/xml"
     - "image/svg"
---
spring:
  config:
    activate:
      on-profile: default
  thymeleaf:
    cache: false
server:
  port: 8080
poker:
  external-url: https://delegation--poker.herokuapp.com  #http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: local-ssl
server:
  ssl:
    key-store: classpath:dev-only-keystore.p12
    key-store-password: changeit
    enabled: true
  port: 8443
poker:
  external-url: https://delegation--poker.herokuapp.com  #https://localhost:8443
---
spring:
  config:
    activate:
      on-profile: heroku
poker:
  external-url: https://delegation--poker.herokuapp.com
management:
  server:
    add-application-context-header: false
